### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bowring**
Adding in Squid3 for SHRIMP.

### CODE REVIEW

**Comment by noahmclean** [comment]
We're just looking for ID-TIMS software at the moment -- maybe we need to change the repository name?

**Comment by brenhinkeller** [comment]
Good point. Yes, changing the name to specify TIMS seems like a good idea.

**Comment by brenhinkeller** [comment]
Unless we want this to include all U-Pb software? Will that get too messy or would there be useful synergy there? My initial thought (and the idea from the workshop) was just TIMS

**Comment by bowring** [comment]
Squid3 is definitely UPb and connected directly to TIMS via dependency on reference materials as well as using the ET_Redux / Topsoil ecosystem.  Topsoil should be considered at some point as well.

**Comment by noahmclean** [comment]
The impetus for this collection of links comes from the U-Pb ID-TIMS workshop, where we decided it would be useful to get all ID-TIMS labs on the same page.  My top priority is to meet this goal.  If we include SIMS software in the current 'Data Reduction' table, we should also include LA-ICPMS projects, and there are about a million of those, both for data reduction and for (e.g. detrital zircon) data interpretation.

I can see how this collection of links would also be useful for others.  We could reasonably structure this so that there's a main U-Pb landing page with links to separate pages each mass spectrometry technique (TIMS, LA-ICPMS, SIMS, Atom Probe Tomography, etc).  That way the TIMS folks can go to their page, SIMS folks if they're interested can go to theirs.  In the short term, we could also add a table for 'Other Techniques' at the bottom of the page.

This might also allow us to bring the U-Pb LA-ICPMS community into the EARTHTIME fold.  Their plasmage.org website is currently down with technical issues -- perhaps we can be of assistance.  But for right now, I just want to check the box for the workshop deliverable.

**Comment by brenhinkeller** [comment]
Name change to EARTHTIME/UPbTIMSSoftware ?

**Pull request closed without merging**
